version: '3.8'

services:
  app:
    container_name: "dev-${USER}" # Update to the name of the app
    build:
      context: ..
      dockerfile: Dockerfile

    volumes:
      #- ..:/workspace:cached
      - /home/oj/Projects:/home/oj/Projects

    # Set environment variables for use within the container
    env_file:
      - .env

    # Overrides default command so things don't shut down after the process ends.
    # command: python /workspace/app/app.py
    # command: sleep infinity
    # stdin_open: true
    # tty: true

    # Uncomment and change port numbers as needed to allow "forwardPorts" in devcontainer.json.
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    # ports:
    #   - 8050:8050

    # Uncomment the next line to use a non-root user for all processes.
    user: $USER 

